In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("Placement.csv")

In [3]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [4]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    str
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    str
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    str
 6   hsc_s           215 non-null    str
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    str
 9   workex          215 non-null    str
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    str
 12  mba_p           215 non-null    float64
 13  status          215 non-null    str
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), str(8)
memory usage: 25.3 KB

In [5]:
dataset.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='str')

In [6]:
dir(dataset)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'degree_p',
 'degree_t',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'etest_p',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'gender',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'hsc_b',
 'hsc_p',
 'hsc_s',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mba_p',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'salary',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sl_no',
 'sort_index',
 'sort_values',
 'specialisation',
 'squeeze',
 'ssc_b',
 'ssc_p',
 'stack',
 'status',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'workex',
 'xs']

In [7]:
dataset["ssc_p"].dtypes

dtype('float64')

In [8]:
for columnName in dataset.columns:
    print(columnName)

sl_no
gender
ssc_p
ssc_b
hsc_p
hsc_b
hsc_s
degree_p
degree_t
workex
etest_p
specialisation
mba_p
status
salary

In [9]:
if(dataset["gender"].dtype=='str'):
    print("qual")
else:
    print("quan")

qual

In [10]:
quan=[]
qual=[]
for columnName in dataset.columns:
    #print(columnName)
    if(dataset[columnName].dtype=='str'):
        #print("qual")
        qual.append(columnName)
    else:
        #print("quan")
        quan.append(columnName)

In [11]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [12]:
qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [13]:
def quanQual(dataset):
    quan=[]
    qual=[]
    for columnName in dataset.columns:
        #print(columnName)
        if(dataset[columnName].dtype=='str'):
            #print("qual")
            qual.append(columnName)
        else:
            #print("quan")
            quan.append(columnName)
    return quan,qual

In [14]:
quanQual(dataset)

(['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'],
 ['gender',
  'ssc_b',
  'hsc_b',
  'hsc_s',
  'degree_t',
  'workex',
  'specialisation',
  'status'])

In [15]:
quan,qual=quanQual(dataset)

In [16]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [17]:
qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [18]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [19]:
dataset["ssc_p"].mean()

np.float64(67.30339534883721)

In [20]:
dataset["ssc_p"].median()

np.float64(67.0)

In [21]:
dataset["ssc_p"].mode()[0]

np.float64(62.0)

In [22]:
dataset.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [23]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)

In [24]:
descriptive["sl_no"]["Mean"]

nan

In [25]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"], columns=quan)

for columnName in quan:
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median", columnName] = dataset[columnName].median()
    descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]

descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0

In [26]:
np.percentile(dataset["ssc_p"],50)

np.float64(67.0)

In [27]:
dataset.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [28]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%",
                                "IQR","1.5IQR","LesserRange","GreaterRange"],columns=quan)
for columnName in quan:
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median", columnName] = dataset[columnName].median()
    descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]
    descriptive.loc["Q1:25%", columnName]=dataset.describe()[columnName]["25%"]
    descriptive.loc["Q2:50%", columnName]=dataset.describe()[columnName]["50%"]
    descriptive.loc["Q3:75%", columnName]=dataset.describe()[columnName]["75%"]
    descriptive.loc["99%",columnName]=np.percentile(dataset.describe()[columnName],100)
    descriptive.loc["Q4:100%", columnName]=dataset.describe()[columnName]["max"]
    descriptive.loc["IQR", columnName]=descriptive[columnName]["Q3:75%"]-descriptive[columnName]["Q1:25%"]
    descriptive.loc["1.5IQR", columnName]=1.5*descriptive[columnName]["IQR"]
    descriptive.loc["LesserRange", columnName]=descriptive[columnName]["Q1:25%"]- descriptive[columnName]["1.5IQR"]
    descriptive.loc["GreaterRange", columnName]=descriptive[columnName]["Q3:75%"]+ descriptive[columnName]["1.5IQR"]
    descriptive.loc["Min", columnName]=dataset[columnName].min()
    descriptive.loc["Max", columnName]=dataset[columnName].max()

In [29]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,215.0,215.0,215.0,215.0,215.0,215.0,940000.0
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5IQR,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
LesserRange,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
GreaterRange,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,37.0,50.0,50.0,51.21,200000.0
Max,215,89.4,97.7,91.0,98.0,77.89,940000.0

In [34]:
LesserRange=[]
GreaterRange=[]

for columnName in quan:
    if(descriptive[columnName]["Min"]<descriptive[columnName]["LesserRange"]):
        LesserRange.append(columnName)
    if(descriptive[columnName]["Max"]>descriptive[columnName]["GreaterRange"]):
        GreaterRange.append(columnName)

In [35]:
LesserRange

['hsc_p']

In [36]:
GreaterRange

['hsc_p', 'degree_p', 'salary']

In [37]:
for column in LesserRange:
    dataset[column][dataset[column]<descriptive[column]["LesserRange"]]=descriptive[column]["LesserRange"]
for column in GreaterRange:
    dataset[column][dataset[column]>descriptive[column]["GreaterRange"]]=descriptive[column]["GreaterRange"]

C:\Users\lokes\AppData\Local\Temp\ipykernel_24316\816909503.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  dataset[column][dataset[column]<descriptive[column]["LesserRange"]]=descriptive[column]["LesserRange"]
C:\Users\lokes\AppData\Local\Temp\ipykernel_24316\816909503.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  dataset[column][dataset[column]>descriptive[column]["GreaterRange"]]=descriptive[column]["GreaterRange"]

Replacing Outliers

In [45]:
dataset[quan] = dataset[quan].astype(float)

for ColumnName in LesserRange:
    dataset.loc[dataset[ColumnName] < descriptive[ColumnName]["LesserRange"],ColumnName] = descriptive[ColumnName]["LesserRange"]

for ColumnName in GreaterRange:
    dataset.loc[dataset[ColumnName] > descriptive[ColumnName]["GreaterRange"],ColumnName] = descriptive[ColumnName]["GreaterRange"]

In [46]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%",
                                "IQR","1.5IQR","LesserRange","GreaterRange"],columns=quan)
for columnName in quan:
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median", columnName] = dataset[columnName].median()
    descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]
    descriptive.loc["Q1:25%", columnName]=dataset.describe()[columnName]["25%"]
    descriptive.loc["Q2:50%", columnName]=dataset.describe()[columnName]["50%"]
    descriptive.loc["Q3:75%", columnName]=dataset.describe()[columnName]["75%"]
    descriptive.loc["99%",columnName]=np.percentile(dataset.describe()[columnName],100)
    descriptive.loc["Q4:100%", columnName]=dataset.describe()[columnName]["max"]
    descriptive.loc["IQR", columnName]=descriptive[columnName]["Q3:75%"]-descriptive[columnName]["Q1:25%"]
    descriptive.loc["1.5IQR", columnName]=1.5*descriptive[columnName]["IQR"]
    descriptive.loc["LesserRange", columnName]=descriptive[columnName]["Q1:25%"]- descriptive[columnName]["1.5IQR"]
    descriptive.loc["GreaterRange", columnName]=descriptive[columnName]["Q3:75%"]+ descriptive[columnName]["1.5IQR"]
    descriptive.loc["Min", columnName]=dataset[columnName].min()
    descriptive.loc["Max", columnName]=dataset[columnName].max()

In [47]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1.0,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,215.0,215.0,215.0,215.0,215.0,215.0,390000.0
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5IQR,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
LesserRange,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
GreaterRange,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1.0,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215.0,89.4,91.15,88.5,98.0,77.89,390000.0

In [48]:
LesserRange=[]
GreaterRange=[]

for columnName in quan:
    if(descriptive[columnName]["LesserRange"]>descriptive[columnName]["Min"]):
        LesserRange.append(columnName)
    if(descriptive[columnName]["GreaterRange"]<descriptive[columnName]["Max"]):
        GreaterRange.append(columnName)

In [49]:
LesserRange

[]

In [50]:
GreaterRange

[]

Frequency

In [52]:
dataset["ssc_p"].value_counts()

ssc_p
62.00    11
63.00    10
67.00     9
73.00     9
52.00     9
         ..
55.68     1
41.00     1
83.33     1
43.00     1
80.60     1
Name: count, Length: 103, dtype: int64

In [53]:
freqTable=pd.DataFrame(columns=["Unique_Values","Frequency","Relative Frequency","Cusum"])

In [54]:
freqTable

Empty DataFrame
Columns: [Unique_Values, Frequency, Relative Frequency, Cusum]
Index: []

In [55]:
freqTable["Unique_Values"]=dataset["ssc_p"].value_counts().index
freqTable["Frequency"]=dataset["ssc_p"].value_counts().values
freqTable["Relative Frequency"]=(freqTable["Frequency"]/103)
freqTable["Cusum"]=freqTable["Relative Frequency"].cumsum()

In [56]:
def freqTable(colunName,dataset):
    freqTable=pd.DataFrame(columns=["Unique_Values","Frequency","Relative Frequency","Cusum"])
    freqTable["Unique_Values"]=dataset[columnName].value_counts().index
    freqTable["Frequency"]=dataset[columnName].value_counts().values
    freqTable["Relative Frequency"]=(freqTable["Frequency"]/103)
    freqTable["Cusum"]=freqTable["Relative Frequency"].cumsum()
    return freqTable

In [57]:
freqTable("",dataset)

    Unique_Values  Frequency  Relative Frequency     Cusum
0        300000.0         22            0.213592  0.213592
1        250000.0         18            0.174757  0.388350
2        390000.0         15            0.145631  0.533981
3        240000.0         15            0.145631  0.679612
4        260000.0          7            0.067961  0.747573
5        200000.0          6            0.058252  0.805825
6        265000.0          6            0.058252  0.864078
7        360000.0          6            0.058252  0.922330
8        220000.0          5            0.048544  0.970874
9        275000.0          5            0.048544  1.019417
10       270000.0          4            0.038835  1.058252
11       210000.0          4            0.038835  1.097087
12       350000.0          3            0.029126  1.126214
13       216000.0          3            0.029126  1.155340
14       252000.0          2            0.019417  1.174757
15       218000.0          2            0.019417  1.194175
16       236000.0          2            0.019417  1.213592
17       204000.0          2            0.019417  1.233010
18       230000.0          2            0.019417  1.252427
19       280000.0          2            0.019417  1.271845
20       276000.0          2            0.019417  1.291262
21       231000.0          1            0.009709  1.300971
22       278000.0          1            0.009709  1.310680
23       320000.0          1            0.009709  1.320388
24       287000.0          1            0.009709  1.330097
25       268000.0          1            0.009709  1.339806
26       336000.0          1            0.009709  1.349515
27       380000.0          1            0.009709  1.359223
28       225000.0          1            0.009709  1.368932
29       233000.0          1            0.009709  1.378641
30       340000.0          1            0.009709  1.388350
31       255000.0          1            0.009709  1.398058
32       285000.0          1            0.009709  1.407767
33       290000.0          1            0.009709  1.417476
34       264000.0          1            0.009709  1.427184
35       295000.0          1            0.009709  1.436893

In [74]:
def Univariate(dataset,quan):
    descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%",
                                "IQR","1.5IQR","LesserRange","GreaterRange"],columns=quan)
    for columnName in quan:
        descriptive.loc["Mean", columnName] = dataset[columnName].mean()
        descriptive.loc["Median", columnName] = dataset[columnName].median()
        descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]
        descriptive.loc["Q1:25%", columnName]=dataset.describe()[columnName]["25%"]
        descriptive.loc["Q2:50%", columnName]=dataset.describe()[columnName]["50%"]
        descriptive.loc["Q3:75%", columnName]=dataset.describe()[columnName]["75%"]
        descriptive.loc["99%",columnName]=np.percentile(dataset.describe()[columnName],100)
        descriptive.loc["Q4:100%", columnName]=dataset.describe()[columnName]["max"]
        descriptive.loc["IQR", columnName]=descriptive[columnName]["Q3:75%"]-descriptive[columnName]["Q1:25%"]
        descriptive.loc["1.5IQR", columnName]=1.5*descriptive[columnName]["IQR"]
        descriptive.loc["LesserRange", columnName]=descriptive[columnName]["Q1:25%"]- descriptive[columnName]["1.5IQR"]
        descriptive.loc["GreaterRange", columnName]=descriptive[columnName]["Q3:75%"]+ descriptive[columnName]["1.5IQR"]
        descriptive.loc["Min", columnName]=dataset[columnName].min()
        descriptive.loc["Max", columnName]=dataset[columnName].max()
    return descriptive

In [75]:
Univariate(dataset,quan)

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1.0,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,215.0,215.0,215.0,215.0,215.0,215.0,390000.0
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5IQR,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
LesserRange,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
GreaterRange,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1.0,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215.0,89.4,91.15,88.5,98.0,77.89,390000.0